version: "3"
services:
  db:
    image: mariadb:10.7
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: todos
      MARIADB_PASSWORD: todos
      MARIADB_DATABASE: todos
      MARIADB_ROOT_PASSWORD: root
